# Generated by Django 2.2 on 2021-01-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210113_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactforms',
            name='Phone_Number',
            field=models.IntegerField(max_length=11),
        ),
    ]
