# Generated by Django 2.2 on 2021-01-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210113_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactforms',
            name='Phone_Number',
            field=models.IntegerField(),
        ),
    ]
